FROM ubuntu:22.04


# Update
RUN apt update && \
	apt upgrade -y


########################
# INSTALL DEPENDENCIES #
########################

# Python deps
RUN apt install --quiet -y \
    python3 python3-dev python3-pip python3-future
RUN pip3 install --upgrade \
    wheel setuptools argcomplete

COPY requirements.txt .
RUN pip3 install --upgrade -r requirements.txt

# Copy volume
COPY . .

EXPOSE 8000


##################
# Final Settings #
##################

ENV force_color_prompt=yes

CMD ["python3", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]